---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    weave-gitops.weave.works/app-identifier: wego-f7dd7f92989e8395387209a716c376a5
  name: wego-fork-test
  namespace: wego-system
spec:
  deployment_type: kustomize
  path: ./
  url: ssh://git@github.com/jrryjcksn/wego-fork-test.git
