apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx3
  namespace: my-nginx3
  labels:
    name: nginx3
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx3
  template:
    metadata:
      namespace: my-nginx3
      labels:
        name: nginx3
    spec:
      containers:
      - name: nginx3
        image: nginx
        ports:
        - containerPort: 80

